version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src/var/www/html:/var/www/html
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3308:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - default
